#include "utils/VertexCFD_Utils_ExplicitTemplateInstantiation.hpp"

#include "VertexCFD_BCStrategy_IncompressibleLSVOFBoundaryFlux.hpp"
#include "VertexCFD_BCStrategy_IncompressibleLSVOFBoundaryFlux_impl.hpp"

VERTEXCFD_INSTANTIATE_TEMPLATE_CLASS_EVAL_NUMSPACEDIM(
    VertexCFD::BoundaryCondition::IncompressibleLSVOFBoundaryFlux)
