title: VERTEX-CFD
description: VERTEX-CFD is a performance portable software package for computational fluid dynamics (CFD) simulations on CPU or GPU architectures.
baseurl: "/VERTEX-CFD"
url: "https://ORNL.github.io"
repository: ORNL/VERTEX-CFD

#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal

permalink: pretty

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

compress_html:
  blanklines: true

# Override purple (default) to ORNL green
color_scheme: ornl_green

logo: docs/figures/vertex_cfd_heated_flow_logo.png
