title: VERTEX-CFD
logo: docs/figures/vertex_cfd_heated_flow_logo.png
description: VERTEX-CFD is a performance portable software package for computational fluid dynamics (CFD) simulations on CPU or GPU architectures.
show_downloads: true
google_analytics:
remote_theme: just-the-docs/just-the-docs
#theme: jekyll-theme-minimal

permalink: pretty

compress_html:
  blanklines: true

# Override purple (default) to ORNL green
color_scheme: ornl_green
