#include "utils/VertexCFD_Utils_ExplicitTemplateInstantiation.hpp"

#include "VertexCFD_Closure_IncompressibleCLSNonReconstructedNormal.hpp"
#include "VertexCFD_Closure_IncompressibleCLSNonReconstructedNormal_impl.hpp"

VERTEXCFD_INSTANTIATE_TEMPLATE_CLASS_EVAL_TRAITS_NUMSPACEDIM(
    VertexCFD::ClosureModel::IncompressibleCLSNonReconstructedNormal)
